language: node_js
node_js:
 - "stable"
services:
  - postgresql
install:
  - npm install

before_script:
  - psql -c 'create database ah_test;' -U postgres

script: npm test
after_success:
  - npm run coverage
