// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:28422c83-bc68-4804-921d-325c73d18281",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_UXBBwHt2r",
    "aws_user_pools_web_client_id": "15q69vsm04t02tv0bgb7d3pcnj",
    "aws_appsync_graphqlEndpoint": "https://xgnbmo53mrfcfddc3cfu3eid7y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rjaxp5tfsng2pie4tf5drkz4qm",
    "aws_cloud_logic_custom": [
        {
            "name": "peopleapi",
            "endpoint": "https://pjg1zanqm5.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "myamplifyappa89c8751247348e689e0f6fcbea555d4",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
